### ISSUE TITLE
Missing font: wingdings 2

### ISSUE THREAD

**Issue by ASopH** [regorxxx/Playlist-Manager-SMP#3]
Hi, this repeat several times in console log. I think, playlist manager is the url.
I resettet my font-cache, restarded and reinstalled wingdings 2 from resource-directory, but it still persits.

[Console.log](https://github.com/regorxxx/Playlist-Manager-SMP/files/6661741/Console.log)

**Comment by regorxxx** [comment]
Yep! I already noticed it, just after the release. Fixed it yesterday, but thanks! Glad to see people is looking at it.

![image](https://user-images.githubusercontent.com/83307074/122302997-67929800-cef2-11eb-85b5-773482c0e604.png)

It's totally safe to ignore it by now. i.e. all text works without problems (in fact is the font drawing the icon at the header), so that's why I have not released a hotfix yet. Just waiting for other changes. 

Anyway, you can download the latest file with the fix directly from the repository. See latest commit ('helpers\playlist_manager_list.js'). Just to not fill the console with that warning
