### ISSUE TITLE
Exporting settings - Where does it save to?

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#4]
Where is the JSON file saved when saving the configuration.

I've checked the folder and sub folders in my portable build: 
**...\foobar2000\profile\scripts\SMP\xxx-scripts**

**Comment by regorxxx** [comment]
.\foobar2000\profile\js_data\

Alternatively you may left click on an autoplaylist and use "Open playlist folder". Since Autoplaylists are saved on json, it will also open the desired folder. (note SMP config is saved within the properties of the panel, you may need to export that if you want a backup of the entire panel and not just the playlists)
