### ISSUE TITLE
This lock is owned by a different component

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#52]
I tried to unlock a selection of playlists after figuring that bit out and entered `RenamePlaylist` but I got this error below.

I thought when it imported them from foo_plorg it would create its own db.

My _profile\playlist_manager_ folder is empty, and only zip files reside in the backup folder. Should the _profile\playlist_manager_ folder not contain something. I tried to move the contents of the zip folder in there but I can't unlock them even though I set the playlist folder to yours after copying the files into that folder.

```Error: Spider Monkey Panel v1.6.1-mod ({F8B0048B-0DC9-40CE-B76A-812260DD1E53}: Playlist-Manager-SMP v0.5.0-beta21 by Regorxxx)
SetPlaylistLockedActions failed:
This lock is owned by a different component

File: playlist_manager_menu.js
Line: 881, Column: 50
Stack trace:
  func/<@playlist_manager_menu.js:881:50
  func@playlist_manager_menu.js:874:17
  _menu/this.btn_up/<@menu_xxx.js:408:15
  _menu/this.btn_up@menu_xxx.js:398:24
  _list/this.playlistMenu@playlist_manager_list.js:1831:37
  _list/this.executeAction@playlist_manager_list.js:1943:94
  _list/this.rbtn_up@playlist_manager_list.js:1273:11
  @main.js:546:23
  fireEvents/</<@callbacks_xxx.js:149:37
  fireEvents/<@callbacks_xxx.js:145:30

'''

**Comment by regorxxx** [comment]
As I said, forget the old component. This has nothing to do with it.

I don't understand what you are doing. There is no way to unlock a playlist via SMP or this script if the playlist is locked by another component.

> I tried to unlock a selection of playlists after figuring that bit out and entered RenamePlaylist 
Entered this? How? There is no input to change locks on this script.

**Comment by regorxxx** [comment]
![plm](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/6d914df6-cb75-4506-bd56-722c3066e678)

There is simply no way to edit a lock not owned by SMP, so I don't understand your steps.

**Comment by regorxxx** [comment]
Ok, got it. You meant the multiple selection menu. I forgot to update that one to be like the contextual menu for single playlists. So now fixed and improved.

**Comment by stephen147** [comment]
So by locked. It's locked by foobar as its an auto play list?

I assumed it had something to do with the old playlist organiser seeing as all my playlists auto populated.

I tried to add them to categories but that isn't working. I take it there's no folders, just categories?

**Comment by regorxxx** [comment]
Playlists may be locked by foobar itself or other components, in such case nothing can edit that lock. Foobar can not edit a lock by a component, a component can not edit a lock by another component, etc. 

Now how you got a playlist locked by something, that's on your side to fix. 

About your other question, please read the pdf.

**Comment by stephen147** [comment]
The pdf file is now opening from the toolbar button on the latest release. Thanks.

BTW, that document is impressive!! Hats off. 

So, categories it is then? Unless I'm missing something? 

I can't seem to add the locked folders to a category.
![2023 06 30 (20-58-06)](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/85be0b73-8ba2-47c4-8d4b-9d4f5f2a8a5b)


Oh, when I right-click on a playlist, shouldn't it get selected also like how you right-click on a directory in Windows?

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/14054664/f910e20a-ba01-420c-8b16-c5d1b448eae8)

**Comment by regorxxx** [comment]
> Oh, when I right-click on a playlist, shouldn't it get selected also like how you right-click on a directory in Windows?
There is no selection here. What you call selection is multiple selection of playlists. A single R. click on a single playlists opens a totally different menu than "selecting" it first. 

I suppose you are asking to append the new playlist to the previous selection. Will check it, since that makes sense. But then the multiple selection context menu would only work -without adding new pls- when r. clicking over the current selection.

> I can't seem to add the locked folders to a category.

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/58290281-d275-4dcc-b82a-65f060113c2b)

They are locked xd obviously you can't edit a locked playlist file. Please read the docs... that thing is answered there and my time is limited. If there is something not explained properly, I'm fine spending time clarifying the docs or fixing it; but don't keep making questions for things I already put at the docs.

![plmlock](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/47c2d59d-1a29-4696-b83e-5cc758d0d8e4)

**Comment by stephen147** [comment]
Thanks. I have looked at that section. These are playlists shown, auto playlists from foo_plorg but it doesn't say in the pdf how these can be converted to work within your manager. This is basically my end goal.

**Comment by regorxxx** [comment]
I don't really understand your question. Foo_plorg doesn't have any type of playlist creation feature.

**Comment by stephen147** [comment]
It does have the ability to create any type of playlist and organise them into folders. Just really confused as to how your component has populated the old playlists into it.

Am I right in saying that any imported auto playlists from that component aren't auto playlists anymore?

**Comment by regorxxx** [comment]
> It does have the ability to create any type of playlist and organise them into folders, ctrl+f and put in your query and add as auto or not. That's how I've created them before.

No. The playlist is NOT created by foo_plorg, that's native foobar. Other thing is the component offering you a shortcut to that native feature. It's not the same. foo_plorg does not store any type of playlist.

> Just really confused as to how your component has populated the old playlists into it.

Because foo_plorg is just an organizer, not a playlist manager with capabilities to store playlists as files. The playlists have been on native foobar all the time, and any organizer can see them. They are just standard autoplaylists.

> Am I right in saying that any imported auto playlists from that component aren't auto playlists anymore?

Again, those are standard auto-playlists, they are not from a component. They should work with anything. Another thing is if they are locked by foo_plorg, in such case ask for help on their thread. I don't support it. If they are locked by foobar itself, that's normal.

**Comment by regorxxx** [comment]
![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/823bd125-d9ed-4f06-b2bf-40ddfebde1e8)
Native foobar. As said, foo_plorg doesn't create anything.

**Comment by stephen147** [comment]
Thank you, I'm just dreading having to recreate 300-odd autoplaylists.

**Comment by regorxxx** [comment]
That's just how foobar works... anyway, I don't think the purpose of autoplaylists is creating a playlist per artist. Obviously you would face this problem at some point with that usage. If you know how to code by yourself, you could automatize it somewhat (but I'm not going to spend my time with that), just saying.

As noted here:
https://hydrogenaud.io/index.php/topic,80705.msg1029648.html#msg1029648

You may ask Peter or @TheQwertiest about exposing the query of autoplaylists. That may change the situation.
