### ISSUE TITLE
[BUG] Error when clicked on settings

### ISSUE THREAD

**Issue by stephen147** [regorxxx/Playlist-Manager-SMP#70]
```
Error: Spider Monkey Panel v1.6.1-mod ({F8B0048B-0DC9-40CE-B76A-812260DD1E53}: Playlist-Manager-SMP v0.11.0 by Regorxxx)
unknown format: 

File: chroma.min.js
Line: 58, Column: 1596
Stack trace:
  g@chroma.min.js:58:1596
  m@chroma.min.js:58:1908
  getColorName@playlist_manager_menu.js:2534:65
  createMenuRightTop/<@playlist_manager_menu.js:2549:71
  createMenuRightTop@playlist_manager_menu.js:2538:12
  func@playlist_manager_list.js:6106:6
  _list/this.lbtn_up@playlist_manager_list.js:1744:14
  @main.js:591:9
  fireEvents/</<@callbacks_xxx.js:149:37
  fireEvents/<@callbacks_xxx.js:145:30

```

**Comment by regorxxx** [comment]
Also try with latest version, I may have fixed something related to this

**Comment by WagnerGFX** [comment]
I had the exact same issue and fixed it by adding `,folderColor,4278190080` at the end of plm_15.

This probably happened because I updated from an older version (something like 0.5.X) that did not have the folder functionality.
Maybe the code is lacking a way to add the property with a default value when it's not found on the setting.

**Comment by regorxxx** [comment]
Thanks for the report, will look for it; yeah, it looks like an update problem with a change on newer versions.

**Comment by regorxxx** [comment]
Fixed!
