### ISSUE TITLE
A way to create playlists from selection inside folder [FEATURE]

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#71]
**Is your feature request related to a problem? Please describe.**
As the documentation states, shortcuts and drag and drop on folders gets applied to every child item. Drag and drop can be used in foo_plorg to quickly create playlists inside folders. This doesn't seem to be currently possible in PM-SMP.

**Describe the solution you'd like**
A way to configure drag and drop to create a new playlist in a folder or a context menu item for folders to create a new playlist from selection.

**Describe alternatives you've considered**
Of course one could create playlists outside the folder and then drag them into the folder, but that is a somewhat tedious extra step.

**Comment by regorxxx** [comment]
I see, essentially this (from the + button) at folders:

![image](https://github.com/regorxxx/Playlist-Manager-SMP/assets/83307074/43386dcc-022e-4bc0-94ee-1e3d235005b2)

I think it should also be possible to tweak the alt+drag n drop behavior to create the new playlist inside the folder under the mouse, instead of putting it at the root.

**Comment by regorxxx** [comment]
Implemented. 
Drag n drop later.

**Comment by regorxxx** [comment]
Drag n drop should work now.
