### ISSUE TITLE
[BUG] Drag & drop interfacing with other components

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#81]
**Describe the bug**
I occasionally try to drag & drop stuff from foo_facets into the playlist manager panel out of habit, but it never works. If I do it in foo_facet's playlist mode, it acts like drag and drop from built in playlist view, but zero tracks actually get sent to the playlist manager. Nevertheless, the tracks get removed from the old playlist, which makes me think that this is something that *could* be fixed from the javascript side, rather than being an SMP limitation, since facets doesn't normally remove tracks during drag&drop, so I figure the script must be aware of what's happening on some level and remove the tracks.

If I try to do it in foo_facets' library mode, the cursor turns into a 🛇 symbol and it doesn't work at all.

**To Reproduce**
1. Open a F2k layout with both a Facets panel and a SMP Playlist Manager panel.
2. Select either playlist mode or library mode in the Facets panel.
3. Drag & drop any item from the Facets panel to SMP-PM.
4. Observe results.

**Expected behavior**
The playlist manager offers creating a new playlist with the title and tracks corresponding to what was selected in Facets.

**System info:**
 - OS: Arch Linux/ Wine
 - Related software: Foobar2000 v2.1.3
 - Github release: 0.15.0 Nightly

**Comment by sonofevil** [comment]
There is nothing in the log.

**Comment by regorxxx** [comment]
The problem is all instances where the panel uses "selection", in fact retrieves the active playlist selection. i.e. if the selection was not in a playlist and selected there, it didn't work. Facets does NOT select the items it sends to the playlist. Same problem would be present in any other panel.

I have changed all instances, it should work fine now. (I would be more cautious about selection from other sources, just in case it doesn't work its due to my changes, please let me know)

**Comment by regorxxx** [comment]
In fact this "problem" applies to all my scripts, but I think most instances naturally needed a playlist anyway so it wasn't a problem. Just in case you use anything more, and want to double check...
