### ISSUE TITLE
[FEATURE] Designating a folder to auto-add new playlists into

### ISSUE THREAD

**Issue by sonofevil** [regorxxx/Playlist-Manager-SMP#83]
**Is your feature request related to a problem? Please describe.**
I like to use keyboard shortcuts from a different component to create new playlists from selections rather than drag & drop or context menus since it is faster/more convenient. This creates a lot of clutter of UI-only playlists however.

**Describe the solution you'd like**
It would be convenient if it was possible to designate a folder as "default" so that loose playlists, especially UI-only playlists not created by the script itself, automatically get added to it. Then the folder could easily be collapsed to hide the clutter.

**Describe alternatives you've considered**
A function assignable to a keyboard shortcut to create a new playlist in a specific folder.

**Comment by regorxxx** [comment]
I am not sure about the convenience of the alternative, since it seems useful just for your particular usage (and thus I would spend time in something I would not use).

It's true creating tons of UI-only playlists clutter the panel, but you have filters for that. i.e. if you don't want to see UI-only playlists, just filter them by playlist type. At any point you can also show UI-only playlists, multiselect them and move them to any folder. It takes 3 seconds.

I may consider the first solution, although that's what tags/categories may be used for. You can filter the view by tag/category, and new playlists created in such view are automatically tagged with that keyword too. 

Anyway I will see if I can design some rules to set where playlists are stored at. At first, I think about this:
- UI-only playlists created outside the panel: so they don't clutter your manually created playlist list.
- UI-only playlists created within the panel.
- New playlists from drag n drop / + button menu / + button shortcut: so you can move them latter if you like the playlist.
- Any other new playlist from panel.

Let me know about anything I missed or ideas.

**Comment by regorxxx** [comment]
Implemented all rules except RegExp and first one (which is a bit complex, since there is no easy way to track when a playlist is new or just the panel is re-reading all UI playlists). Let me know about how it works for the rest

**Comment by sonofevil** [comment]
Unfortunately the settings seem to have no effect. Playlists still don't get added to the folder.
![Screenshot_20240611_184422](https://github.com/regorxxx/Playlist-Manager-SMP/assets/19374890/8f20bdb6-341e-49c4-85c4-a1122c09d7ad)

Sorry for the late response. My health hasn't been the best.

**Comment by regorxxx** [comment]
The external UI playlists are not working as noted above. That entry is just a placeholder right now.

Are the other cases working? (you have to create UI playlist within the panel)

There is no hurry for this, just report whenever you can :)

**Comment by sonofevil** [comment]
Ah, ok, got it. Yeah, playlists created via the panel are added to the folder just fine.

**Comment by regorxxx** [comment]
Great, will either look for a way to implement the external UI case or remove the entry. It is not easy.

**Comment by regorxxx** [comment]
The missing bit has been added on latest commit. Closing it.
